version: 2
updates:
  - package-ecosystem: npm
    directory: /vbird-esi
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /vbird-esi/src-tauri
    schedule:
      interval: weekly
